language: elm

elm: 0.19.1
elm-format: 0.8.3

install:
  - npm install -g uglify-js

script:
  - elm make src/Main.elm --output dist/elm.js --optimize
  - uglifyjs dist/elm.js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe" | uglifyjs --mangle --output=dist/elm.min.js
  - elm-format --validate .

deploy:
  local_dir: ./dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch:
      master
